### ISSUE TITLE
ImportError: cannot import name 'DisjointSet' from 'core.utils.misc' 

### ISSUE THREAD

**Issue by QiaolinLu** [AlgoMole/MolCRAFT#10]
Hi, thanks for your great work. I try to `eval_distribution.ipynb` in the `test` folder. I meet an error `ImportError: cannot import name 'DisjointSet' from 'core.utils.misc' `, but it seems that no DisjointSet in the misc.py.  `from pose_check_train_set import CDTrainSet` also runs the error.  How can I solve the problem? Thanks!

**Comment by qky18** [comment]
Hi, if there's no further discussion, I will close the issue in 24 hrs.
Feel free to reopen it if the problem persists.
