### ISSUE TITLE
Discrepancy Between Reproduced Results and Reported Data

### ISSUE THREAD

**Issue by explorer1212** [AlgoMole/MolCRAFT#11]
Dear authors, 
    I have been working on reproducing the results from your paper using the last.ckpt but have noticed some differences between the results I obtained and those reported in the paper.
    
![image](https://github.com/user-attachments/assets/ab86bd71-5c7d-49c9-bd1d-418172faff62)

the strain is ok, but the vina score,vina min, and vina dock do not meet expectations

Do I need to do any further processing on the results?

**Comment by qky18** [comment]
Hi, thanks for your interest in our work!

If you're sampling by default settings, i.e. `sample_num_atoms` set to 'ref', it matches the results in our paper that

|            | Vina Score Avg | Vina Score Med | Vina Min Avg | Vina Min Med | Vina Dock Avg | Vina Dock Med | Strain Energy 25% | Strain Energy 75% | SA   | QED | Molecule Size |
|------------|----------------|----------------|--------------|--------------|---------------|---------------|-------------------|-------------------|------|-----|---------------|
| Ours       | -6.59          | -7.05          | -7.24        | -7.26        | -7.80         | -7.92         | 83                | 510               | 0.69 | 0.5 | 22.7          |
| Reproduced | -6.55          | -6.95          | -7.14        | -7.14        | -7.78         | -7.80         | 26                | 327               | 0.67 |     |               |

the slight differences in strain energy might stem from the fact that we've set [this](https://github.com/AlgoMole/MolCRAFT/blob/master/train_bfn.py#L212) to 'prior' for the results in our paper.

For other model variants (Ours-small & Ours-large), some prespecified number of atoms are needed, which we adopt the same size as Pocket2Mol & DecompDiff (Opt-prior), respectively.

**Comment by explorer1212** [comment]
Thank you very much!

**Comment by qky18** [comment]
You're welcome :)
