### ISSUE TITLE
how to evaluate posecheck/rmsd

### ISSUE THREAD

**Issue by explorer1212** [AlgoMole/MolCRAFT#12]
Hello authors, 
     I now have the generated.pt which have the generated molecules, however, the eval_posecheck.py and the eval_rmsd.py in the test folder need to take .sdf files as input, so how can I transform the .pt into the .sdf format, or other ways to solve this issue.
    Thanks very much!!!

**Comment by explorer1212** [comment]
If possible, could you share the code? Thanks very much!

**Comment by qky18** [comment]
Hi, sorry for the late reply.
The following code snippets might be useful in transforming the `.pt` files into multiple `.sdf`:

```python
import torch
from rdkit import Chem
path = 'vina_docked.pt' # or 'generated.pt' for the raw generation results (without vina etc.), in that way you might need to manually set some molecule properties for further evaluation
results = torch.load(path) 
for idx, r in enumerate(results):
    mol = r['mol']
    if path == 'generated.pt'
        mol.SetProp('_Name', r['ligand_filename'])  # for PoseCheck & Dock to locate the proteins
    with Chem.SDWriter(f'{idx}.sdf') as writer:
        writer.write(mol)
```

**Comment by explorer1212** [comment]
Thank you very much!!!
