### ISSUE TITLE
The test.yaml file was not found

### ISSUE THREAD

**Issue by xxrelax** [AlgoMole/MolCRAFT#2]
Hi, thanks for your wonderful work!

I want to try to generate some molecules, but I can't find the test.yaml file, could you please tell me how to configure this file？

**Comment by xxrelax** [comment]
Oh！thank you for your reply, I can solve this problem now.

**Comment by Atomu2014** [comment]
> Hi, thanks for your wonderful work!
> 
> I want to try to generate some molecules, but I can't find the test.yaml file, could you please tell me how to configure this file？

Hi, test.yaml is the same as default.yaml. I've updated README.

Thanks
