### ISSUE TITLE
vinascore nan

### ISSUE THREAD

**Issue by explorer1212** [AlgoMole/MolCRAFT#9]
when I run the testing method using this command "python train_bfn.py --test_only --no_wandb --ckpt_path ./checkpoints/last.ckpt", the vina score has always benn "nan", how can I solve this problem 
![image](https://github.com/user-attachments/assets/09ea5cbc-fc35-47d7-9b24-097707599540)

**Comment by explorer1212** [comment]
I found that the test_set is not exist, how can I solve this problem
![image](https://github.com/user-attachments/assets/54015032-8cd5-4d34-8946-217df8d213c5)

**Comment by explorer1212** [comment]
oh I found the problem.

**Comment by qky18** [comment]
> oh I found the problem.

Hi, the nan values will be reported if Vina detects some error such as misaligned ligands with pocket, or file missing.
Did the nan score still persist?

**Comment by explorer1212** [comment]
> > oh I found the problem.
> 
> Hi, the nan values will be reported if Vina detects some error such as misaligned ligand with the pocket, or files missing. Did the nan score still persist?

Thanks for your reply, I have found the solution, this is due to the missing test set, sorry for bother you, I did not find a way to close this issue.
